### ISSUE TITLE
Як ви створили слов'янську клавіатуру?

### ISSUE THREAD

**Issue by IlyasTarpan** [medzuslovjansky/slovjanski.site#1]
Добрий день! Наскільки я знаю, ви створили слов'янську клавіатуру для Gboard. Я хотів би запитати, як ви створили таку клавіатуру. 
Справа в тому, що мені теж потрібно створити свою клавіатуру, і бажано саме на Gboard. Я хотів би створити кримськотатарську клавіатуру на арабіці, але я не знаю як це зробити.
Не могли б ви мені підказати, як це зробити?
З повагою, Ільяс

**Comment by noomorph** [comment]
Доброго дня, конкретно з проєкту цим займався Андрєй Усачов:

> Я розпакував Gboard, за аналогією створив два нових IME (вхідні методи, клавіатури) — для МС-латиниці та МС-кирилиці. Для кожного додав по одній розкладці: російську та QWERTY. Потім зв’язався з людиною, яка займається модами для Gboard на форумі 4PDA. Я попросив його запакувати все це назад у нову версію Gboard.

**Comment by IlyasTarpan** [comment]
Дякую за відповідь!

Можете будь ласка поділитися контактами цього Андрєя Усачева?

**Comment by IlyasTarpan** [comment]
> Доброго дня, конкретно з проєкту цим займався Андрєй Усачов:
> 
> > Я розпакував Gboard, за аналогією створив два нових IME (вхідні методи, клавіатури) — для МС-латиниці та МС-кирилиці. Для кожного додав по одній розкладці: російську та QWERTY. Потім зв’язався з людиною, яка займається модами для Gboard на форумі 4PDA. Я попросив його запакувати все це назад у нову версію Gboard.



Дякую за відповідь!

Можете будь ласка поділитися контактами цього Андрєя Усачева?
